main: de.kirimcdev.minecraft.plugins.kiricore.main.Main
name: kiriCore
version: a20200620-1
author: kirimcdev

softdepend:
  - "Essentials"

commands:
  afk:
    description: Marks you or another player as AFK or back
    usage: /afk [Player]
  afklist:
    description: Shows all players who are currently marked as AFK
    usage: /afklist
  isafk:
    description: Checks and shows if a specific player is marked as AFK at the moment
    usage: /isafk <Player>
  clearchat:
    description: Clears the chat by sending some empty messages.
    usage: /clearchat [anyways|console]
  exit:
    description: Stops the server. (Just an alias for /stop)
    usage: /exit