main: de.kiridevs.kiricore.main.Main

name: kiriCore
version: 0.9.0
api-version: 1.16
author: kiriDevs

website: https://github.com/kiriDevs/kiriCore

description: >
  kiriCore is an open-source library for Minecraft Plugins,
  used by kiriDevs for all their plugins, but can also be used by other
  developers for their own projects. It also provides some core features
  like commands that can be useful on many servers.

commands:
  afk:
    description: Toggle your AFK-Status!
    usage: /afk
    permission: kiri.core.afk
  isafk:
    description: Check if a specific player is marked as AFK at the moment!
    usage: /isafk <Playername>
    permission: kiri.core.afk.check
  afklist:
    description: Print a list of all players marked as AFK at the moment!
    usage: /afklist
    permission: kiri.core.afk.list
  rename:
    description: Rename the currently held item
    usage: /rename <new item name>
    permission: kiri.core.rename
  pvp:
    description: Get or change the current status of PVP on the server!
    usage: /afk [(yes, y, on, true) / (no, n, off, false)]
    permissions: kiri.core.pvp
