name: Deploy on GH Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Deploy to Maven Central using OSSRH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout released repo state
      uses: actions/checkout@v2

    - name: Set up JDK14
      uses: actions/setup-java@v1
      with:
        java-version: "14"
        java-package: jdk
        architecture: x64

    # Using actions/setup-java again overrides the settings.xml
    - name: Setup settings.xml for Sonatype OSSRH deployment
      uses: actions/setup-java@v1
      with:
        java-version: "14"
        java-package: jdk
        architecture: x64

        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.RELEASE_GPG_KEY }}
        gpg-passphrase: RELEASE_GPG_KEY_PASSPHRASE

    - name: Build and Stage deployment using Maven
      run: mvn deploy --file pom.xml
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        RELEASE_GPG_KEY_PASSPHRASE: ${{ secrets.RELEASE_GPG_KEY_PASSPHRASE }}

    # This extra step is necessary since autoReleaseAfterClose is set to false in pom.xml
    - name: Deploy stageing repository from OSSRH to Maven Central
      run: mvn nexus-staging:release
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
