name: Maven Build
on: [push, pull_request]

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current state of the repo
      uses: actions/checkout@v2
      
    - name: Set up JDK14
      uses: actions/setup-java@v1
      with:
        java-version: "14"
        java-package: jdk
        architecture: x64
      
    - name: Build project with Maven
      run: mvn verify --file pom.xml
